# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d90f898fc3055b644ce65aa2b3f932a96f774a14a339f7c03baa9dbc4efc3d9b0f51be9da22c2a05629bc44f0552a126cac8ada6a495e3183ce82b3cc12bf1e

test:
  secret_key_base: 055b0bac5d3a6ac61a07772772e6413ab5c78e3af2f2e085392ad73dff676b239140284768b4d42c5d58bbbe97424c3540dbb20ea501f384f1138879c95c2ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
